name: orbit
description: Aplicación ORBIT - Telefonía satelital
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^4.0.0

  cupertino_icons: ^1.0.6

  shared_preferences: ^2.2.2

  http: ^1.2.1
  flutter_webrtc: ^1.2.1
  flutter_sound: ^9.30.0
  permission_handler: ^12.0.1
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3  
  cloud_firestore: ^6.1.1
  firebase_messaging: ^16.1.0
  encrypt: ^5.0.3
  image_picker: ^1.2.1
  web_socket_channel: ^3.0.3
  file_picker: ^10.3.8
  logger: ^2.6.2
  connectivity_plus: ^7.0.0
  google_weather_flutter: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/ 

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/orbit_logo.png
